language: java
addons:
  sonarcloud:
    organization: "marinakrivonosova"
    token:
      secure:   $SONAR_TOKEN

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=marinakrivonosova_ts-backend